### ISSUE TITLE
Non UA-... property IDs are not supported - support for  Google Analytics 4 Properties 

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/plugin-GoogleAnalyticsImporter#150] opened 2020-11-27 00:31 UTC
Currently, property IDs that do not have the UA-* prefix result in an error when imported:

```
values must match the following regular expression: 'UA-[0-9]+-[0-9]+'"
```

This doesn't appear to originate from the plugin which only uses a regex to find the account ID if it has one, so must be coming from the SDK or API itself.

**Comment by mattab** [comment] 2020-12-29 05:53
We got another similar report recently:

> how can i import data from new Google Analytics 4 Properties that have no Views, only Data Streams? They also have no UA- in the beginning, my Property ID is only 1234569037. I am getting this error message when i try to import: Error
 { "error": { "code": 400, "message": "Invalid value '1234569037.'. Values must match the following regular expression: 'UA-[0-9]+-[0-9]+'", "errors": [ { "message": "Invalid value '1234569037.'. Values must match the following regular expression: 'UA-[0-9]+-[0-9]+'", "domain": "global", "reason": "invalidParameter" } ] } }

**Comment by KarthikRaja1388** [comment] 2021-11-02 21:25
Another report:  
I cant import the google analytics data, my ID is not UA format but G-XXX. so Matomo doesnt let me import any past data.

**Comment by Starker3** [comment] 2021-11-12 02:32
We have another request regarding this ticket from a user today. They are unable to import their historical data from GA due to the importer not yet supporting non-UA property IDs

**Comment by MatomoForumNotifications** [comment] 2022-03-25 14:36
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/import-data-from-google-analytics-confused-with-google-ids/45283/2

**Comment by AltamashShaikh** [comment] 2022-05-12 06:53
For documentation
Unsupported/Incompatible Doc/Metrics
```
ga:exits, ga:entrances, ga:pageDownloadTime, ga:pageLoadSample, ga:goal{$gaIdGoal}Completions, ga:goal{$gaIdGoal}Value, ga:goal{$gaIdGoal}ConversionRate

ga:bounces(Bounces) is no more supported in GA4 but can be calculated using the bounceRate metric (bounceRate * sessions)
```
No Conditions for goals to fire, as goals are converted to events.
Couldn't find anything for segments in GA4 yet.

**Comment by AltamashShaikh** [comment] 2022-06-08 09:11
Hello everyone added support for GA4 in this branch #245 and would be great if someone can test this and share early feedback.

You can refer this [faq](https://matomo.org/faq/plugins/faq_21/) on how to add plugin.

If you have added via git you can simply checkout to `150-GA4-Import` branch.

Any other difficulties please mention here.

If you have already configured Oauth you need to enable 2 more additional APIs
1. Google Analytics Data API 
2. Google Analytics Admin API 

Please [Refer this guide](https://matomo.org/faq/general/set-up-google-analytics-import/) to setup GA/GA4 Import in Matomo.

**Comment by bsutton** [comment] 2022-07-22 05:17
Is this live on cloud?

I've just gone through the guide https://matomo.org/faq/general/set-up-google-analytics-import/

The problem is the import UI is still asking for a UA- property id and a view ID neither of which GA4 appear to have?

**Comment by AltamashShaikh** [comment] 2022-07-22 05:19
Hey @bsutton 
We haven’t merged the GA4 importer code.
Hopefully once Matomo 4.11 releases we can merge and release it

**Comment by Marion5** [comment] 2022-07-26 09:23
Yeah, we would also be happy about a GA4 importer!

**Comment by MacRX17** [comment] 2022-08-10 07:12
Anything new about the GA4 Importer? Currently it is not possible to import our GA4 data into Matomo. Thanks alot!

**Comment by AltamashShaikh** [comment] 2022-08-10 08:20
Matomo 4.11 is just released we will wait for couple of weeks to plan the new version release of this plugin, which contains GA4 Importer

**Closed as completed** 2022-09-05 04:56 UTC
