### ISSUE TITLE
Import cannot run if shell_exec()/exec() is not available

### ISSUE THREAD

**Issue by siksmsi** [matomo-org/plugin-GoogleAnalyticsImporter#14] opened 2019-11-06 14:05 UTC
After starting an Import from Google Analytics and click on the running import task, I get the following error: 

An error occurred
The parameter 'period' isn't set in the Request, and a default value wasn't provided.

I have set the start and end date in the format 2015-01-01 and 2019-11-05. 

What goes wrong?  

In the status field are the following informations: 

started
 
Last Day Imported: -                         
Last Day Archived: -                        
Import End Date: 2019-11-06 

Import Start Time: 2019-11-06 14:00:49                         
Last Resume Time: 2019-11-06 14:00:49 

Estimated finish in unbekannt days.
-- | -- | -- | --

Nothing changed since hours.

**Comment by diosmosis** [comment] 2019-11-06 15:00
This has to do w/ the URL, something is trying to access the `period` parameter but it's not always set for admin pages. I should be able to fix this later.

You should be able to workaround it by adding `period=day&date=today` to the URL on the admin page (let me know if that doesn't work).

**Comment by siksmsi** [comment] 2019-11-06 15:06
Thank you. If I add this parameter, the admin page would load correct. 

BUT the main problem is, that the import does  not run correctly. I start the Import but it does not import the data. It creates the site and imports the site name etc. but do not import the data. Since hours this status: 

started

Last Day Imported: -
Last Day Archived: -
Import End Date: 2019-11-06

Import Start Time: 2019-11-06 14:00:49
Last Resume Time: 2019-11-06 14:00:49

Estimated finish in unbekannt days.
-- | -- | -- | --

**Comment by diosmosis** [comment] 2019-11-06 17:19
This is likely a different issue... can you look for the log for that import? It should be in `tmp/logs/` and start with `gaimportlog.<siteId>`. If it's not there you can try initiating the import using the command line w/ the `-vvv` option (see https://matomo.org/docs/google-analytics-importer/#using-the-command-line).

**Comment by siksmsi** [comment] 2019-11-06 19:36
Attached you will find the log file. Do you get some information out of this file? 

[gaimportlog.10.log.koelner-newsjournal.de.log](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/3816374/gaimportlog.10.log.koelner-newsjournal.de.log)

**Comment by diosmosis** [comment] 2019-11-06 19:54
That looks like the matomo login screen, did you try to access it through the browser? It may not exist in which case to debug further we'd have to run the command.

**Comment by diosmosis** [comment] 2019-11-07 06:59
In case you're not able to run CLI commands on your install, it is also possible to debug by changing some individual files in your matomo. If this is something you can/rather do let me know.

**Comment by siksmsi** [comment] 2019-11-07 08:06
I am not able to run CLI commands. But I am able to changing some individual files. What do I have to do?

**Comment by diosmosis** [comment] 2019-11-08 00:00
@siksmsi replace '/path/to/matomo/plugins/GoogleAnalyticsImporter/Tasks.php` with https://gist.github.com/diosmosis/3e1ae6d9c6d642cd6f2046c9f045e855

then replace '/path/to/matomo/plugins/GoogleAnalyticsImporter/angularjs/import-scheduler/import-scheduler.controller.js` with https://gist.github.com/diosmosis/cc2b1a67f1d1c6c6747761be104d6999

(make sure to backup the files so it will be easy to revert the changes once we figure out what's going on)

Then deactivate & activate the GoogleAnalyticsImporter plugin so the new JS will be loaded, clear your browser cache and reload the import page. When you run an import it should print relevant output to page. If it doesn't, you may have to look in the networks tab for an HTTP request w/ `module=GoogleAnalyticsImporter&action=startImport` in the URL to get the output. That will hopefully provide some insight.

**Comment by diosmosis** [comment] 2019-11-08 00:22
I couldn't reproduce the other issue you experienced. To get more information for that one, change this line: https://github.com/matomo-org/matomo/blob/3.x-dev/index.php#L24 to `define('PIWIK_PRINT_ERROR_BACKTRACE', true);`

**Comment by siksmsi** [comment] 2019-11-08 06:19
Thank you again. I replaced the two files, deactivated the plugin. Deleted the cache. Activated it again. But no error output on the import screen. No change in the status. And now I could  not start a new import. It shows the attaced error in the console after clicking the button. There is no http request with "module=GoogleAnalyticsImporter&action=startImport" in the network tab. Does it help, if I provide login credentials to you?

**Comment by diosmosis** [comment] 2019-11-08 06:33
@siksmsi yes providing login credentials would help, can you email support@matomo.org? We can debug further from there.

**Comment by siksmsi** [comment] 2019-11-08 06:46
I have send you the data via email right now.

**Comment by diosmosis** [comment] 2019-11-08 22:01
The problem here is that shell_exec()/exec() is not available to use in PHP on the machine. We can add an alternative mechanism to initiate imports in the background via API methods using curl in the background (ie, using a client side timeout of ~1-2s). Though this would be a problem if the server cut off the request after a certain amount of time.

Another alternative would be to insert records via API methods so the script can be run on a local computer instead of a server. That has a downside in that the user would have to manually run the import every day until finished (due to API request limits).

cc @mattab / @tsteur

**Comment by siksmsi** [comment] 2019-11-09 05:46
Thank you for your support diosmosis. 

I need only one import. Because we want to completely switch over to Matomo. Do you have a workaround for me, which I can use in short term? 

Would it be helpful, if I can grant a SSH access? The provided FTP data could also be used for SSH. 

How many API requests would be used? I ask because of the free limit of Google.

**Comment by siksmsi** [comment] 2019-11-09 05:47
Or would it be possible to activate shell_exec()/exec()  on an 1&1/Ionos webhosting account?

**Comment by siksmsi** [comment] 2019-11-09 06:07
I now have access via SSH. If I start the import via ./console googleanalyticsimporter:import-reports --property=UA-#######-1 --view=###### --dates=2015-03-15,2019-11-05 I get the error "permission denied". 

I send you the correct login credentials for SSH via email.

**Comment by siksmsi** [comment] 2019-11-10 07:32
Here is what happens, when I start the import via SSH: 

![1](https://user-images.githubusercontent.com/30862637/68540568-90f15680-0394-11ea-88b0-1f9fcc53869e.jpg)
![2](https://user-images.githubusercontent.com/30862637/68540569-9189ed00-0394-11ea-9c1e-658985577127.jpg)

**Comment by diosmosis** [comment] 2019-11-10 08:29
@siksmsi sent you a reply by email

**Comment by diosmosis** [comment] 2019-11-19 11:46
Closing in favor of #17

**Closed by diosmosis** 2019-11-19 11:46 UTC
