### ISSUE TITLE
Label column not found

### ISSUE THREAD

**Issue by prathers** [matomo-org/plugin-GoogleAnalyticsImporter#29] opened 2019-12-01 17:29 UTC
After starting migrating GA data, I get an error in dashboard and different views:
`Label column not found in the table to add in addDataTable() - in plugin Referrers`

Matomo 3.13.0

**Comment by diosmosis** [comment] 2019-12-01 20:38
Can you provide a screenshot and the URL you were viewing when the error occurs?

**Comment by diosmosis** [comment] 2019-12-01 21:05
Also, what version of the importer are you using?

**Comment by prathers** [comment] 2019-12-02 08:12
URLs:
`https://domain.tld/index.php?module=CoreHome&action=index&idSite=9&period=range&date=previous30&updated=1#?idSite=9&period=range&date=2007-06-02,2007-12-01&segment=&category=Dashboard_Dashboard&subcategory=1`
and:
`https://webstat.rather.dk/index.php?module=CoreHome&action=index&idSite=9&period=range&date=previous30&updated=1#?idSite=9&period=range&date=2007-06-02,2007-07-31&segment=&category=General_Visitors&subcategory=General_Overview`
I've just begun the migration and it's only when date range is on migrated data.

> GoogleAnalyticsImporter v1.0.6

<img width="1032" alt="http___www_vikingeskibsmuseet_dk_-_From_2007-06-02_to_2007-07-31_-_Web_Analytics_Reports_-_Matomo" src="https://user-images.githubusercontent.com/3508890/69940873-95b4b080-14e3-11ea-99b5-3a0709aab316.png">
<img width="1033" alt="http___www_vikingeskibsmuseet_dk_-_From_2007-06-02_to_2007-07-31_-_Web_Analytics_Reports_-_Matomo" src="https://user-images.githubusercontent.com/3508890/69940887-9e0ceb80-14e3-11ea-8a25-427be4c7829f.png">

**Comment by diosmosis** [comment] 2019-12-02 14:22
Can you check the referrers reports during a single day? Does it work and are there any funny rows that are missing labels?

Can you email the logs for the import to benaka@innocraft.com (you would be able to find them in the `tmp/logs/gaimportlog.$idSite.log` files)? And, also, would you be willing to provide access to your GA or Matomo?

**Comment by prathers** [comment] 2019-12-03 07:07
There is no referrers at all for the migrated period.
Unfortunately, the importer overwrites the log-file every night.

Can it be that the data from GA is too old (<2008)?

**Comment by diosmosis** [comment] 2019-12-03 15:21
> There is no referrers at all for the migrated period.

Then it's definitely experiencing an issue with the GA referrers data and failing to import it.

> Can it be that the data from GA is too old (<2008)?

Yes, that's probably the overall reason, the GA API response changes based on how old the data is, and sometimes for old data the API will randomly respond with nothing. I can probably find the cause and a fix if you can provide temporary access to your GA account. Or alternatively you could add some extra debug logs to see what data the GA API is returning for the old dates.

**Comment by diosmosis** [comment] 2019-12-07 00:46
Hi @prathers I've recently released version 1.1.0 of this plugin which includes an option to enable verbose logging. If you follow the instructions in the user guide for this feature: https://matomo.org/docs/google-analytics-importer/#troubleshooting, you should be able to provide us with information we can use to debug and hopefully solve this issue.

**Comment by prathers** [comment] 2019-12-07 06:22
I'll try that. Unfortunately it's not an option to give access to the GA account but I'll try the verbose logging and get back to you

**Comment by prathers** [comment] 2019-12-07 16:38
It'll boil an output the coming night and I'll mail you the result

**Comment by diosmosis** [comment] 2019-12-12 03:20
Closing since the last email indicates this now works.

**Closed by diosmosis** 2019-12-12 03:20 UTC
