### ISSUE TITLE
Cannot Import GA4 Property, saying that the Matomo Site-ID doesn't exist

### ISSUE THREAD

**Issue by wolfgang-hartl** [matomo-org/plugin-GoogleAnalyticsImporter#291] opened 2022-10-26 06:30 UTC
Hey there, 

I am trying to import an existing GA4 Property, but every time I run the importer a message (exception) get's logged saying that the  Site ID doesn't exist. See the Text from the log below (I've replaced my domain with example.com). 

The Installation of Matomo itself worked pretty fine and the system check said that everything is ok and all requirements are fullfilled.
I have no Idea what to do to make it work! :-(

PS: Of course I've checked if the site was created in Matomo, and a Site (with ID 9) was created!

Thanks in Advance for your help! 

Cheers

![Bildschirmfoto 2022-10-26 um 08 29 03](https://user-images.githubusercontent.com/75800215/197951237-78dae3dc-de73-490d-83dd-247d65c0f0b6.png)

--------------------------------------- MESSAGE FROM THE LOG -----------------------------------------------------
ERROR [2022-10-26 06:21:13] 2614344  Uncaught exception: /var/www/vhosts/example.com/example.com/httpdocs/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php(302): Site ID 9 does not exist. [Query: , CLI mode: 1]

                             
  [Exception]                
  Site ID 9 does not exist.  
                             

Exception trace:
 () at /var/www/vhosts/example.com/example.com/httpdocs/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php:302
 Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports->getIdSite() at /var/www/vhosts/example.com/example.com/httpdocs/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php:76
 Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports->executeImpl() at /var/www/vhosts/example.com/example.com/httpdocs/plugins/GoogleAnalyticsImporter/Commands/ImportGA4Reports.php:54
 Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportGA4Reports->execute() at /var/www/vhosts/example.com/example.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/vhosts/example.com/example.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vhosts/example.com/example.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at n/a:n/a
 call_user_func() at /var/www/vhosts/example.com/example.com/httpdocs/core/Console.php:135
 Piwik\Console->Piwik\{closure}() at /var/www/vhosts/example.com/example.com/httpdocs/core/Access.php:670
 Piwik\Access::doAsSuperUser() at /var/www/vhosts/example.com/example.com/httpdocs/core/Console.php:136
 Piwik\Console->doRunImpl() at /var/www/vhosts/example.com/example.com/httpdocs/core/Console.php:87
 Piwik\Console->doRun() at /var/www/vhosts/example.com/example.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/vhosts/example.com/example.com/httpdocs/console:32

googleanalyticsimporter:import-ga4-reports [--property="..."] [--dates="..."] [--idsite="..."] [--cvar-count="..."] [--skip-archiving] [--mobile-app] [--timezone="..."] [--extra-custom-dimension="..."]

**Comment by snake14** [comment] 2022-10-26 20:50
Hi @Wolfi1616 . I'm sorry to hear that you're experiencing this problem. If this error is occurring, it looks like you're providing the `--idsite` parameter when you execute the import command. Is there a specific reason you're doing this? [According to the documentation](https://matomo.org/faq/general/running-the-google-analytics-import/#setup-an-import-using-the-command-line-for-ga4), that option is only for resuming an existing import. If your intent was to create a new import for an existing site, I apologise that the plugin doesn't yet support that functionality. If you are in fact trying to resume an existing import, you might try outputting the actual exception that was caught around [line 302](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Commands/ImportGA4Reports.php#L302) or remove the try/catch so that the original exception is surfaced and hopefully get a better indication of what's going on. Another thing to watch out for is that we have seen some unexpected behaviour with Matomo running on PHP 8.1 and if you continue to experience problems, you might try switching to PHP 8.0.

I'm going to go ahead and close this issue. Please let me know if you think that it should remain open.

**Closed as completed** 2022-10-26 20:53 UTC

**Comment by Pazekal90** [comment] 2022-12-07 16:47
@snake14: Same Problem here with Universal Analytics. 
SiteID is valid and also checked with another php version. My Example here is PHP 7.4

![image](https://user-images.githubusercontent.com/25208775/206239648-43453e66-ac4e-4f7e-96f4-25719527968c.png)

**Comment by snake14** [comment] 2022-12-07 20:17
@Pazekal90 I'm sorry to hear that you're experiencing this problem. As this issue has been closed, it would be better to post on the [Matomo forum](https://forum.matomo.org/) or create a new issue referencing this one. Either way, we'd need more information. Are you trying to import a new site or restart an existing import? If you're trying to import a new site, you don't provide the `--idsite` option. If you're trying to restart an existing import, then there might be a problem if you've confirmed that a site with the ID you provided does indeed exist in your Matomo database. I just tried running `./console googleanalyticsimporter:import-reports --idsite=2 --verbose` on my local machine, which has a site 2, and it failed because the import for that site had already completed. If you need further assistance, please check the forum or contact support. If you are able to confirm that it's a bug, please open a new issue and provide as much detail as possible to help us reproduce the problem. Thank you
