### ISSUE TITLE
Big difference in imported numbers between Google Analytics and Matomo

### ISSUE THREAD

**Issue by denarie** [matomo-org/plugin-GoogleAnalyticsImporter#59] opened 2020-01-16 09:57 UTC
I had the importer running vor a while. I compared the visitor numbers , at first, they are quite similar.
The importer ist still running regularly and the websites tracking is still using Google Analytics.
Suddenly the numbers in Matomo dropped to 0, 1 or 2 visitors, even if Google Analytics shows about 20 visitors.
I upgraded the importer to use the newest version, but this did not change it.
What could be the reasion for this?
Thank you very much!

**Comment by diosmosis** [comment] 2020-01-16 10:51
Hi @denarie , sorry to hear this... are these visits for days or other periods? Could you provide some screenshots (the visitors overview for one day + the same day in GA)?

**Comment by diosmosis** [comment] 2020-01-16 11:19
Another question: do you have tracking setup for this site in Matomo as well as GA?

**Comment by denarie** [comment] 2020-01-16 11:53
The visitors are for days, see screenshots.
No, the tracking setup for the site is still GA.

![google_analytics](https://user-images.githubusercontent.com/8998950/72522975-1bf04080-385f-11ea-8c3c-18c6eb47a931.jpg)
![google_analytics2](https://user-images.githubusercontent.com/8998950/72522976-1c88d700-385f-11ea-8d83-d1fa97bdf4ad.jpg)
![matomo](https://user-images.githubusercontent.com/8998950/72522977-1c88d700-385f-11ea-9e6c-d3350201c9ae.png)
![matomo2](https://user-images.githubusercontent.com/8998950/72522978-1d216d80-385f-11ea-810d-c2129790ed8c.png)

**Comment by diosmosis** [comment] 2020-01-16 11:59
@denarie for december 19th, can you check what the visitor log displays?

**Comment by denarie** [comment] 2020-01-16 12:43
The graph for december 17th to 20th 
![visitors](https://user-images.githubusercontent.com/8998950/72526125-fa468780-3865-11ea-84d0-bc31b562c4d0.png)
And the visitor log for the same period says "Es stehen keine Daten für diesen Bericht zur Verfügung.", so no data available.

**Comment by diosmosis** [comment] 2020-01-16 13:13
@denarie Using google translate I see "besuche" is "visit" and "nutzer" is "user", correct? In this case we're comparing incorrect metrics. Visits are imported as sessions in GA and visitors in Matomo are imported as users (so we should compare visits w/ sessions, and visitors w/ users). When doing so do you still see a discrepancy? If so, I'm not sure what could cause it, but if you're willing to provide read only access to your GA account I can try to reproduce it (in this case email benaka@innocraft.com).

**Comment by diosmosis** [comment] 2020-01-16 15:10
@denarie one other thing you could try is to start a new import for Dec 19th and enable debug logging via the checkbox. Then email the logs for the new site ID to me and I'll see if there's something there (the logs are a file named tmp/logs/gaimportlog.$idSite.log).

**Comment by Mich-es** [comment] 2020-01-16 16:37
Hi denarie,
and diosmosis, 

i got the same problem with one property:
![grafik](https://user-images.githubusercontent.com/58422824/72543453-093d3200-3886-11ea-9f46-391d1e0b793d.png)
![grafik](https://user-images.githubusercontent.com/58422824/72543737-781a8b00-3886-11ea-9480-757791189153.png)


And i got another problem too - Can you please check the following:
Go to visitors, select a date range of at least 10 days and check whether the graphic in the upper part matches the visitors in the lower part:
https://forum.matomo.org/t/bug-google-analytics-importer-does-not-work-correctly/35430

Thanks!

**Comment by diosmosis** [comment] 2020-01-16 16:43
@Mich-es if you can provide read only access to your GA it would be the easiest way to find the cause and resolve the issue.

**Comment by Mich-es** [comment] 2020-01-16 17:03
yes, i can.
can u give me a E-Mail?

**Comment by diosmosis** [comment] 2020-01-16 17:03
@Mich-es please use benaka@innocraft.com

**Comment by Mich-es** [comment] 2020-01-17 07:27
ok, e-mail was sent

**Comment by diosmosis** [comment] 2020-01-17 07:30
hi @Mich-es, that could help, but I was actually looking for read only access to your Google Analytics account so I could try an import and see what happens.

EDIT: I could use your matomo to try an import as well, but without ssh access to the server I wouldn't be able to go through the logs. It's much easier if you could authorize my email to access your GA property.

**Comment by Mich-es** [comment] 2020-01-17 07:34
its done and you have access

**Comment by diosmosis** [comment] 2020-01-17 07:36
@Mich-es got the email, I'll look into this in the next couple hours and see what's wrong.

**Comment by diosmosis** [comment] 2020-01-17 09:50
fyi @Mich-es I responded to your email.

@denarie the issues you are experiencing seem unrelated to @Mich-es 's, would you be able to provide any type of access?

**Comment by denarie** [comment] 2020-01-17 14:48
@diosmosis Sorry for my late reply. I just started a new import with debug option on. I will sent you the log via email.
EDIT: just sent the logs.

**Comment by diosmosis** [comment] 2020-08-01 23:44
Fixed by #66

**Closed as completed by diosmosis** 2020-08-01 23:44 UTC
