### ISSUE TITLE
encountered URL twice in result set

### ISSUE THREAD

**Issue by pioc92** [matomo-org/plugin-GoogleAnalyticsImporter#4] opened 2019-09-04 14:35 UTC
Hi all, i tried your plugin but my import jobs failed with this error status:

encountered URL twice in result set

**Comment by diosmosis** [comment] 2019-09-05 01:40
Hi @pioc92, thanks for the bug report! I think this is due to a typo, which I've fixed in git master. Would you be able to try the latest changes by checking the plugin out from git?

**Comment by pioc92** [comment] 2019-09-05 12:36
hum i tried and i have the same error but not with the same url...

**Comment by diosmosis** [comment] 2019-09-05 13:12
@pioc92 can you try running the CLI command with the idsite that was created and `-vvv`? This should provide a stack trace for the error.

**Comment by diosmosis** [comment] 2019-09-06 08:15
@pioc92 one other question: the error message should have the URL it encountered twice (ie, "encountered URL twice in result set: /blah/blah/blah"), do you see that?

**Comment by pioc92** [comment] 2019-09-07 17:13
Yes i see that:

Error message: Unexpected error: encountered URL twice in result set: https://routeur4g.fr/discussions/discussion/344/700mhz-agregation-antenne

I can't test in CLI mode, sorry

**Comment by pioc92** [comment] 2019-09-07 17:19
I found in google analytics the 2 urls:
https://routeur4g.fr/discussions/discussion/344/700mhz-agregation-antenne
https://routeur4g.fr/discussions/discussion/344/700mhz-agrégation-antenne

That's why the plugin can't import the urls!

**Comment by diosmosis** [comment] 2019-09-07 17:25
Ah, interesting, one has unicode... Ok, I can look into a fix now, thanks for looking into this!

**Comment by diosmosis** [comment] 2019-09-11 08:22
@pioc92 I tried, but I'm still not able to reproduce this (for me the URLs are treated correctly as separate URLs). Can you tell me what php version you are using? And if possible can you try running the following php code and tell me what the output is:

```
<?php

$test = [];

$test['https://routeur4g.fr/discussions/discussion/344/700mhz-agregation-antenne'] = 1;
$test['https://routeur4g.fr/discussions/discussion/344/700mhz-agrégation-antenne'] = 2;

var_export($test);
```

Otherwise, if you're willing to provide temporary access to your GA account (for this one property), I can try to reproduce it some more. Email support@matomo.org and I can explain how to provide us with access.

**Comment by pioc92** [comment] 2019-09-11 09:44
hi,

result of the test : 
array (
  'https://routeur4g.fr/discussions/discussion/344/700mhz-agregation-antenne' => 1,
  'https://routeur4g.fr/discussions/discussion/344/700mhz-agrégation-antenne' => 2,
)

i can give you an access, dm me a mail

**Comment by pioc92** [comment] 2019-09-11 09:45
php version 7.3.9

**Comment by pioc92** [comment] 2019-09-11 09:50
php PHP Version 7.1.24-1+ubuntu16.04.1+deb.sury.org+1

**Comment by diosmosis** [comment] 2019-09-11 14:02
@pioc92 dm through the forums you mean? AFAIK the private message system on github doesn't exist anymore.

**Comment by pioc92** [comment] 2019-09-11 16:20
I made an account on matomo forum.

**Comment by pioc92** [comment] 2019-09-11 16:27
I send a mail to support@matomo.com

**Closed** 2019-09-13 07:20 UTC
