### ISSUE TITLE
Google Anlaytic Import (GA4)

### ISSUE THREAD

**Issue by fwertel** [matomo-org/plugin-GoogleAnalyticsImporter#224] opened 2022-02-18 10:28 UTC
Hello,

We would like to import GA4 data in Matomo.

It doesn't seem doable - the Google Analytics Import requires the field "Google Analytics Property ID" which doesn't exist with GA4. 

Is there another option (available API, etc...) ? 

## Summary

Being able to import GA4 data in matomo.

## Your Environment

Matomo's cloud version.

**Comment by tsteur** [comment] 2022-02-20 18:44
Hi @fwertel  thanks for creating this issue. I'll close this issue as a duplicate of https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/150 You can watch #150 if you want to be updated about that issue.

**Closed as completed by tsteur** 2022-02-20 18:44 UTC
Labels: duplicate
